apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction
  labels:
    app: auction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auction
  template:
    metadata:
      labels:
        app: auction
    spec:
      containers:
        - name: auction
          image: auction:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_HTTP_ADDR
              value: ":8080"
            - name: HZ_CLUSTERNAME
              value: "auction-cluster"
            - name: HZ_MEMBERS
              value: "hazelcast-1:5701,hazelcast-2:5701,hazelcast-3:5701"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auction
  labels:
    app: auction
spec:
  selector:
    app: auction
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auction
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auction
  minReplicas: 2
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

