basePath: /
definitions:
  golang-sba-hazelcast_internal_auction.Auction:
    properties:
      description:
        type: string
      ends_at:
        type: string
      id:
        type: string
      seller_id:
        type: string
      starts_at:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
  description: Online auction API built with Space Based Architecture using Hazelcast.
  title: Auction SBA API
  version: 0.1.0
paths:
  /auctions:
    post:
      consumes:
      - application/json
      description: Creates a new auction
      parameters:
      - description: Auction
        in: body
        name: auction
        required: true
        schema:
          $ref: '#/definitions/golang-sba-hazelcast_internal_auction.Auction'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
      summary: Create an auction
  /auctions/active:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/golang-sba-hazelcast_internal_auction.Auction'
            type: array
        "500":
          description: Internal Server Error
      summary: List active auctions
  /work:
    get:
      parameters:
      - default: 50
        description: Duration in milliseconds
        in: query
        name: ms
        type: integer
      responses:
        "200":
          description: OK
      summary: Consume CPU cycles for autoscaling tests
swagger: "2.0"
